name: CI/CD Pipeline - Basic Testing Only

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 3. Install dependencies
      - name: Install development dependencies
        run: |
          pip install -r docs/requirements-dev.txt

      # 4. Run Python tests (run basic tests only)
      - name: Run basic tests
        run: |
          pytest tests/test_example.py -v  # Only run basic tests (no API tests)
