name: CI/CD Pipeline - Minimal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 3. Install development dependencies
      - name: Install development dependencies
        run: |
          pip install -r docs/requirements-dev.txt

      # 4. Run Python tests
      - name: Run tests
        run: |
          pytest

      # 5. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t nextgenio .

